// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Ban struct {
	ID              int64
	BannedUserID    sql.NullInt64
	BannedIpAddress sql.NullString
	AdminUserID     sql.NullInt64
	Reason          sql.NullString
	ExpiresAt       sql.NullTime
	CreatedAt       time.Time
}

type Friendship struct {
	UserOneID    int64
	UserTwoID    int64
	Status       string
	ActionUserID int64
}

type Player struct {
	ID        int64
	UserID    int64
	Name      string
	BestScore int64
	Color     int32
	CreatedAt time.Time
}

type User struct {
	ID                int64
	Username          string
	PasswordHash      string
	BaomainData       json.RawMessage
	UsernameLowercase string
	IsAdmin           bool
	CreatedAt         time.Time
}
