// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: pkg/packets/game_packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Id
	//	*Packet_LoginRequest
	//	*Packet_RegisterRequest
	//	*Packet_DenyResponse
	//	*Packet_SaveDataRequest
	//	*Packet_PlayerData
	//	*Packet_PlayerDataUpdate
	//	*Packet_EnterWorldRequest
	//	*Packet_MapData
	//	*Packet_PlayerMoveRequest
	//	*Packet_PlayerPositionUpdate
	//	*Packet_PlayerEnterMap
	//	*Packet_PlayerLeaveMap
	//	*Packet_Chat
	//	*Packet_FriendRequestList
	//	*Packet_FriendRequestSend
	//	*Packet_FriendRequestResponse
	//	*Packet_FriendRemove
	//	*Packet_FriendListUpdate
	//	*Packet_TradeRequestSend
	//	*Packet_TradeRequestReceive
	//	*Packet_TradeRequestResponse
	//	*Packet_TradeUpdate
	//	*Packet_TradeAccept
	//	*Packet_TradeCancel
	//	*Packet_TradeStart
	//	*Packet_AdminBanRequest
	//	*Packet_AdminActionResponse
	//	*Packet_AdminGiveItemRequest
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetId() *IdMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetDenyResponse() *DenyResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_DenyResponse); ok {
			return x.DenyResponse
		}
	}
	return nil
}

func (x *Packet) GetSaveDataRequest() *SaveDataRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_SaveDataRequest); ok {
			return x.SaveDataRequest
		}
	}
	return nil
}

func (x *Packet) GetPlayerData() *Player {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerData); ok {
			return x.PlayerData
		}
	}
	return nil
}

func (x *Packet) GetPlayerDataUpdate() *PlayerDataUpdate {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerDataUpdate); ok {
			return x.PlayerDataUpdate
		}
	}
	return nil
}

func (x *Packet) GetEnterWorldRequest() *EnterWorldRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_EnterWorldRequest); ok {
			return x.EnterWorldRequest
		}
	}
	return nil
}

func (x *Packet) GetMapData() *MapData {
	if x != nil {
		if x, ok := x.Msg.(*Packet_MapData); ok {
			return x.MapData
		}
	}
	return nil
}

func (x *Packet) GetPlayerMoveRequest() *PlayerMoveRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerMoveRequest); ok {
			return x.PlayerMoveRequest
		}
	}
	return nil
}

func (x *Packet) GetPlayerPositionUpdate() *PlayerPositionUpdate {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerPositionUpdate); ok {
			return x.PlayerPositionUpdate
		}
	}
	return nil
}

func (x *Packet) GetPlayerEnterMap() *PlayerEnterMap {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerEnterMap); ok {
			return x.PlayerEnterMap
		}
	}
	return nil
}

func (x *Packet) GetPlayerLeaveMap() *PlayerLeaveMap {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerLeaveMap); ok {
			return x.PlayerLeaveMap
		}
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetFriendRequestList() *FriendRequestList {
	if x != nil {
		if x, ok := x.Msg.(*Packet_FriendRequestList); ok {
			return x.FriendRequestList
		}
	}
	return nil
}

func (x *Packet) GetFriendRequestSend() *FriendRequestSend {
	if x != nil {
		if x, ok := x.Msg.(*Packet_FriendRequestSend); ok {
			return x.FriendRequestSend
		}
	}
	return nil
}

func (x *Packet) GetFriendRequestResponse() *FriendRequestResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_FriendRequestResponse); ok {
			return x.FriendRequestResponse
		}
	}
	return nil
}

func (x *Packet) GetFriendRemove() *FriendRemove {
	if x != nil {
		if x, ok := x.Msg.(*Packet_FriendRemove); ok {
			return x.FriendRemove
		}
	}
	return nil
}

func (x *Packet) GetFriendListUpdate() *FriendListUpdate {
	if x != nil {
		if x, ok := x.Msg.(*Packet_FriendListUpdate); ok {
			return x.FriendListUpdate
		}
	}
	return nil
}

func (x *Packet) GetTradeRequestSend() *TradeRequestSend {
	if x != nil {
		if x, ok := x.Msg.(*Packet_TradeRequestSend); ok {
			return x.TradeRequestSend
		}
	}
	return nil
}

func (x *Packet) GetTradeRequestReceive() *TradeRequestReceive {
	if x != nil {
		if x, ok := x.Msg.(*Packet_TradeRequestReceive); ok {
			return x.TradeRequestReceive
		}
	}
	return nil
}

func (x *Packet) GetTradeRequestResponse() *TradeRequestResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_TradeRequestResponse); ok {
			return x.TradeRequestResponse
		}
	}
	return nil
}

func (x *Packet) GetTradeUpdate() *TradeUpdate {
	if x != nil {
		if x, ok := x.Msg.(*Packet_TradeUpdate); ok {
			return x.TradeUpdate
		}
	}
	return nil
}

func (x *Packet) GetTradeAccept() *TradeAccept {
	if x != nil {
		if x, ok := x.Msg.(*Packet_TradeAccept); ok {
			return x.TradeAccept
		}
	}
	return nil
}

func (x *Packet) GetTradeCancel() *TradeCancel {
	if x != nil {
		if x, ok := x.Msg.(*Packet_TradeCancel); ok {
			return x.TradeCancel
		}
	}
	return nil
}

func (x *Packet) GetTradeStart() *TradeStart {
	if x != nil {
		if x, ok := x.Msg.(*Packet_TradeStart); ok {
			return x.TradeStart
		}
	}
	return nil
}

func (x *Packet) GetAdminBanRequest() *AdminBanRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_AdminBanRequest); ok {
			return x.AdminBanRequest
		}
	}
	return nil
}

func (x *Packet) GetAdminActionResponse() *AdminActionResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_AdminActionResponse); ok {
			return x.AdminActionResponse
		}
	}
	return nil
}

func (x *Packet) GetAdminGiveItemRequest() *AdminGiveItemRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_AdminGiveItemRequest); ok {
			return x.AdminGiveItemRequest
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Id struct {
	// --- Connection & Auth ---
	Id *IdMessage `protobuf:"bytes,3,opt,name=id,proto3,oneof"`
}

type Packet_LoginRequest struct {
	LoginRequest *LoginRequest `protobuf:"bytes,4,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequest `protobuf:"bytes,5,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Packet_DenyResponse struct {
	DenyResponse *DenyResponse `protobuf:"bytes,7,opt,name=deny_response,json=denyResponse,proto3,oneof"`
}

type Packet_SaveDataRequest struct {
	SaveDataRequest *SaveDataRequest `protobuf:"bytes,25,opt,name=save_data_request,json=saveDataRequest,proto3,oneof"`
}

type Packet_PlayerData struct {
	PlayerData *Player `protobuf:"bytes,22,opt,name=player_data,json=playerData,proto3,oneof"` // Sent on login with full player save data. CORRECTED.
}

type Packet_PlayerDataUpdate struct {
	PlayerDataUpdate *PlayerDataUpdate `protobuf:"bytes,29,opt,name=player_data_update,json=playerDataUpdate,proto3,oneof"`
}

type Packet_EnterWorldRequest struct {
	// --- World Interaction (NEW) ---
	EnterWorldRequest *EnterWorldRequest `protobuf:"bytes,50,opt,name=enter_world_request,json=enterWorldRequest,proto3,oneof"` // C->S: "I'm ready to enter the game world"
}

type Packet_MapData struct {
	MapData *MapData `protobuf:"bytes,51,opt,name=map_data,json=mapData,proto3,oneof"` // S->C: Here is all the data for the map you are on
}

type Packet_PlayerMoveRequest struct {
	PlayerMoveRequest *PlayerMoveRequest `protobuf:"bytes,52,opt,name=player_move_request,json=playerMoveRequest,proto3,oneof"` // C->S: "I want to move to this tile"
}

type Packet_PlayerPositionUpdate struct {
	PlayerPositionUpdate *PlayerPositionUpdate `protobuf:"bytes,53,opt,name=player_position_update,json=playerPositionUpdate,proto3,oneof"` // S->C: A player (maybe you) has moved
}

type Packet_PlayerEnterMap struct {
	PlayerEnterMap *PlayerEnterMap `protobuf:"bytes,54,opt,name=player_enter_map,json=playerEnterMap,proto3,oneof"` // S->C: A new player has appeared on your map
}

type Packet_PlayerLeaveMap struct {
	PlayerLeaveMap *PlayerLeaveMap `protobuf:"bytes,55,opt,name=player_leave_map,json=playerLeaveMap,proto3,oneof"` // S->C: A player has left your map
}

type Packet_Chat struct {
	// --- Social & Admin ---
	Chat *ChatMessage `protobuf:"bytes,20,opt,name=chat,proto3,oneof"`
}

type Packet_FriendRequestList struct {
	FriendRequestList *FriendRequestList `protobuf:"bytes,30,opt,name=friend_request_list,json=friendRequestList,proto3,oneof"`
}

type Packet_FriendRequestSend struct {
	FriendRequestSend *FriendRequestSend `protobuf:"bytes,31,opt,name=friend_request_send,json=friendRequestSend,proto3,oneof"`
}

type Packet_FriendRequestResponse struct {
	FriendRequestResponse *FriendRequestResponse `protobuf:"bytes,32,opt,name=friend_request_response,json=friendRequestResponse,proto3,oneof"`
}

type Packet_FriendRemove struct {
	FriendRemove *FriendRemove `protobuf:"bytes,33,opt,name=friend_remove,json=friendRemove,proto3,oneof"`
}

type Packet_FriendListUpdate struct {
	FriendListUpdate *FriendListUpdate `protobuf:"bytes,34,opt,name=friend_list_update,json=friendListUpdate,proto3,oneof"`
}

type Packet_TradeRequestSend struct {
	TradeRequestSend *TradeRequestSend `protobuf:"bytes,40,opt,name=trade_request_send,json=tradeRequestSend,proto3,oneof"`
}

type Packet_TradeRequestReceive struct {
	TradeRequestReceive *TradeRequestReceive `protobuf:"bytes,41,opt,name=trade_request_receive,json=tradeRequestReceive,proto3,oneof"`
}

type Packet_TradeRequestResponse struct {
	TradeRequestResponse *TradeRequestResponse `protobuf:"bytes,42,opt,name=trade_request_response,json=tradeRequestResponse,proto3,oneof"`
}

type Packet_TradeUpdate struct {
	TradeUpdate *TradeUpdate `protobuf:"bytes,43,opt,name=trade_update,json=tradeUpdate,proto3,oneof"`
}

type Packet_TradeAccept struct {
	TradeAccept *TradeAccept `protobuf:"bytes,44,opt,name=trade_accept,json=tradeAccept,proto3,oneof"`
}

type Packet_TradeCancel struct {
	TradeCancel *TradeCancel `protobuf:"bytes,45,opt,name=trade_cancel,json=tradeCancel,proto3,oneof"`
}

type Packet_TradeStart struct {
	TradeStart *TradeStart `protobuf:"bytes,46,opt,name=trade_start,json=tradeStart,proto3,oneof"`
}

type Packet_AdminBanRequest struct {
	AdminBanRequest *AdminBanRequest `protobuf:"bytes,26,opt,name=admin_ban_request,json=adminBanRequest,proto3,oneof"`
}

type Packet_AdminActionResponse struct {
	AdminActionResponse *AdminActionResponse `protobuf:"bytes,27,opt,name=admin_action_response,json=adminActionResponse,proto3,oneof"`
}

type Packet_AdminGiveItemRequest struct {
	AdminGiveItemRequest *AdminGiveItemRequest `protobuf:"bytes,28,opt,name=admin_give_item_request,json=adminGiveItemRequest,proto3,oneof"`
}

func (*Packet_Id) isPacket_Msg() {}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_DenyResponse) isPacket_Msg() {}

func (*Packet_SaveDataRequest) isPacket_Msg() {}

func (*Packet_PlayerData) isPacket_Msg() {}

func (*Packet_PlayerDataUpdate) isPacket_Msg() {}

func (*Packet_EnterWorldRequest) isPacket_Msg() {}

func (*Packet_MapData) isPacket_Msg() {}

func (*Packet_PlayerMoveRequest) isPacket_Msg() {}

func (*Packet_PlayerPositionUpdate) isPacket_Msg() {}

func (*Packet_PlayerEnterMap) isPacket_Msg() {}

func (*Packet_PlayerLeaveMap) isPacket_Msg() {}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_FriendRequestList) isPacket_Msg() {}

func (*Packet_FriendRequestSend) isPacket_Msg() {}

func (*Packet_FriendRequestResponse) isPacket_Msg() {}

func (*Packet_FriendRemove) isPacket_Msg() {}

func (*Packet_FriendListUpdate) isPacket_Msg() {}

func (*Packet_TradeRequestSend) isPacket_Msg() {}

func (*Packet_TradeRequestReceive) isPacket_Msg() {}

func (*Packet_TradeRequestResponse) isPacket_Msg() {}

func (*Packet_TradeUpdate) isPacket_Msg() {}

func (*Packet_TradeAccept) isPacket_Msg() {}

func (*Packet_TradeCancel) isPacket_Msg() {}

func (*Packet_TradeStart) isPacket_Msg() {}

func (*Packet_AdminBanRequest) isPacket_Msg() {}

func (*Packet_AdminActionResponse) isPacket_Msg() {}

func (*Packet_AdminGiveItemRequest) isPacket_Msg() {}

// C->S: Client sends this after login to say they are ready to spawn in-world.
type EnterWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterWorldRequest) Reset() {
	*x = EnterWorldRequest{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterWorldRequest) ProtoMessage() {}

func (x *EnterWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterWorldRequest.ProtoReflect.Descriptor instead.
func (*EnterWorldRequest) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{1}
}

// S->C: Sent once when the player enters a map. Contains all initial state.
type MapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Players       []*OtherPlayer         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"` // We can add `repeated Npc npcs = 3;` here later.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapData) Reset() {
	*x = MapData{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapData) ProtoMessage() {}

func (x *MapData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapData.ProtoReflect.Descriptor instead.
func (*MapData) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{2}
}

func (x *MapData) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MapData) GetPlayers() []*OtherPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

// C->S: Client requests to move to a new tile.
type PlayerMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetX       int32                  `protobuf:"varint,1,opt,name=target_x,json=targetX,proto3" json:"target_x,omitempty"`
	TargetY       int32                  `protobuf:"varint,2,opt,name=target_y,json=targetY,proto3" json:"target_y,omitempty"`
	Direction     int32                  `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"` // 0=Down, 1=Up, 2=Left, 3=Right
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMoveRequest) Reset() {
	*x = PlayerMoveRequest{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMoveRequest) ProtoMessage() {}

func (x *PlayerMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMoveRequest.ProtoReflect.Descriptor instead.
func (*PlayerMoveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerMoveRequest) GetTargetX() int32 {
	if x != nil {
		return x.TargetX
	}
	return 0
}

func (x *PlayerMoveRequest) GetTargetY() int32 {
	if x != nil {
		return x.TargetY
	}
	return 0
}

func (x *PlayerMoveRequest) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

// S->C: Server confirms a move and broadcasts it to clients on the map.
type PlayerPositionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // The ID of the player who moved.
	NewX          int32                  `protobuf:"varint,2,opt,name=new_x,json=newX,proto3" json:"new_x,omitempty"`
	NewY          int32                  `protobuf:"varint,3,opt,name=new_y,json=newY,proto3" json:"new_y,omitempty"`
	Direction     int32                  `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerPositionUpdate) Reset() {
	*x = PlayerPositionUpdate{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPositionUpdate) ProtoMessage() {}

func (x *PlayerPositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPositionUpdate.ProtoReflect.Descriptor instead.
func (*PlayerPositionUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerPositionUpdate) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerPositionUpdate) GetNewX() int32 {
	if x != nil {
		return x.NewX
	}
	return 0
}

func (x *PlayerPositionUpdate) GetNewY() int32 {
	if x != nil {
		return x.NewY
	}
	return 0
}

func (x *PlayerPositionUpdate) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

// S->C: Broadcast to players on a map when a new player enters.
type PlayerEnterMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *OtherPlayer           `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnterMap) Reset() {
	*x = PlayerEnterMap{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnterMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnterMap) ProtoMessage() {}

func (x *PlayerEnterMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnterMap.ProtoReflect.Descriptor instead.
func (*PlayerEnterMap) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerEnterMap) GetPlayer() *OtherPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

// S->C: Broadcast to players on a map when a player leaves.
type PlayerLeaveMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeaveMap) Reset() {
	*x = PlayerLeaveMap{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeaveMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeaveMap) ProtoMessage() {}

func (x *PlayerLeaveMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeaveMap.ProtoReflect.Descriptor instead.
func (*PlayerLeaveMap) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerLeaveMap) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// A simplified player object for representing other players in the world.
type OtherPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Direction     int32                  `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	SpriteId      string                 `protobuf:"bytes,6,opt,name=sprite_id,json=spriteId,proto3" json:"sprite_id,omitempty"` // e.g. "player_red_boy"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtherPlayer) Reset() {
	*x = OtherPlayer{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtherPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherPlayer) ProtoMessage() {}

func (x *OtherPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherPlayer.ProtoReflect.Descriptor instead.
func (*OtherPlayer) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{7}
}

func (x *OtherPlayer) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *OtherPlayer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OtherPlayer) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *OtherPlayer) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *OtherPlayer) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *OtherPlayer) GetSpriteId() string {
	if x != nil {
		return x.SpriteId
	}
	return ""
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{8}
}

func (x *IdMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Color         int32                  `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

type DenyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponse) Reset() {
	*x = DenyResponse{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponse) ProtoMessage() {}

func (x *DenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponse.ProtoReflect.Descriptor instead.
func (*DenyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{11}
}

func (x *DenyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SaveDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDataRequest) Reset() {
	*x = SaveDataRequest{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDataRequest) ProtoMessage() {}

func (x *SaveDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDataRequest.ProtoReflect.Descriptor instead.
func (*SaveDataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{12}
}

func (x *SaveDataRequest) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

// Sent on successful login, contains the entire player save data blob.
type Player struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaomainJsonData string                 `protobuf:"bytes,3,opt,name=baomain_json_data,json=baomainJsonData,proto3" json:"baomain_json_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{13}
}

func (x *Player) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetBaomainJsonData() string {
	if x != nil {
		return x.BaomainJsonData
	}
	return ""
}

type PlayerDataUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaomainJsonData string                 `protobuf:"bytes,1,opt,name=baomain_json_data,json=baomainJsonData,proto3" json:"baomain_json_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerDataUpdate) Reset() {
	*x = PlayerDataUpdate{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDataUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDataUpdate) ProtoMessage() {}

func (x *PlayerDataUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDataUpdate.ProtoReflect.Descriptor instead.
func (*PlayerDataUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerDataUpdate) GetBaomainJsonData() string {
	if x != nil {
		return x.BaomainJsonData
	}
	return ""
}

// --- Chat ---
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{15}
}

func (x *ChatMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// --- Friends ---
type FriendRequestList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestList) Reset() {
	*x = FriendRequestList{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestList) ProtoMessage() {}

func (x *FriendRequestList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestList.ProtoReflect.Descriptor instead.
func (*FriendRequestList) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{16}
}

type FriendRequestSend struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUsername string                 `protobuf:"bytes,1,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FriendRequestSend) Reset() {
	*x = FriendRequestSend{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestSend) ProtoMessage() {}

func (x *FriendRequestSend) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestSend.ProtoReflect.Descriptor instead.
func (*FriendRequestSend) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{17}
}

func (x *FriendRequestSend) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

type FriendRequestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUsername string                 `protobuf:"bytes,1,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	Accept         bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FriendRequestResponse) Reset() {
	*x = FriendRequestResponse{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestResponse) ProtoMessage() {}

func (x *FriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestResponse.ProtoReflect.Descriptor instead.
func (*FriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{18}
}

func (x *FriendRequestResponse) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

func (x *FriendRequestResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type FriendRemove struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUsername string                 `protobuf:"bytes,1,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FriendRemove) Reset() {
	*x = FriendRemove{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRemove) ProtoMessage() {}

func (x *FriendRemove) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRemove.ProtoReflect.Descriptor instead.
func (*FriendRemove) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{19}
}

func (x *FriendRemove) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

type FriendListUpdate struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Friends       []*FriendListUpdate_Friend `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListUpdate) Reset() {
	*x = FriendListUpdate{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListUpdate) ProtoMessage() {}

func (x *FriendListUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListUpdate.ProtoReflect.Descriptor instead.
func (*FriendListUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{20}
}

func (x *FriendListUpdate) GetFriends() []*FriendListUpdate_Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

// --- Trading ---
type TradeRequestSend struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUsername string                 `protobuf:"bytes,1,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradeRequestSend) Reset() {
	*x = TradeRequestSend{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeRequestSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRequestSend) ProtoMessage() {}

func (x *TradeRequestSend) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRequestSend.ProtoReflect.Descriptor instead.
func (*TradeRequestSend) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{21}
}

func (x *TradeRequestSend) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

type TradeRequestReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUsername  string                 `protobuf:"bytes,1,opt,name=from_username,json=fromUsername,proto3" json:"from_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeRequestReceive) Reset() {
	*x = TradeRequestReceive{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeRequestReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRequestReceive) ProtoMessage() {}

func (x *TradeRequestReceive) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRequestReceive.ProtoReflect.Descriptor instead.
func (*TradeRequestReceive) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{22}
}

func (x *TradeRequestReceive) GetFromUsername() string {
	if x != nil {
		return x.FromUsername
	}
	return ""
}

type TradeRequestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUsername string                 `protobuf:"bytes,1,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	Accept         bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradeRequestResponse) Reset() {
	*x = TradeRequestResponse{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRequestResponse) ProtoMessage() {}

func (x *TradeRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRequestResponse.ProtoReflect.Descriptor instead.
func (*TradeRequestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{23}
}

func (x *TradeRequestResponse) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

func (x *TradeRequestResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type TradeUpdate struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	IsLockedIn    bool                     `protobuf:"varint,1,opt,name=is_locked_in,json=isLockedIn,proto3" json:"is_locked_in,omitempty"`
	Rings         int64                    `protobuf:"varint,2,opt,name=rings,proto3" json:"rings,omitempty"`
	Items         []*TradeUpdate_TradeItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Chao          []*TradeUpdate_TradeChao `protobuf:"bytes,4,rep,name=chao,proto3" json:"chao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeUpdate) Reset() {
	*x = TradeUpdate{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeUpdate) ProtoMessage() {}

func (x *TradeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeUpdate.ProtoReflect.Descriptor instead.
func (*TradeUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{24}
}

func (x *TradeUpdate) GetIsLockedIn() bool {
	if x != nil {
		return x.IsLockedIn
	}
	return false
}

func (x *TradeUpdate) GetRings() int64 {
	if x != nil {
		return x.Rings
	}
	return 0
}

func (x *TradeUpdate) GetItems() []*TradeUpdate_TradeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TradeUpdate) GetChao() []*TradeUpdate_TradeChao {
	if x != nil {
		return x.Chao
	}
	return nil
}

type TradeAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLockedIn    bool                   `protobuf:"varint,1,opt,name=is_locked_in,json=isLockedIn,proto3" json:"is_locked_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeAccept) Reset() {
	*x = TradeAccept{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeAccept) ProtoMessage() {}

func (x *TradeAccept) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeAccept.ProtoReflect.Descriptor instead.
func (*TradeAccept) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{25}
}

func (x *TradeAccept) GetIsLockedIn() bool {
	if x != nil {
		return x.IsLockedIn
	}
	return false
}

type TradeCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeCancel) Reset() {
	*x = TradeCancel{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeCancel) ProtoMessage() {}

func (x *TradeCancel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeCancel.ProtoReflect.Descriptor instead.
func (*TradeCancel) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{26}
}

func (x *TradeCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TradeStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtherUsername string                 `protobuf:"bytes,1,opt,name=other_username,json=otherUsername,proto3" json:"other_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeStart) Reset() {
	*x = TradeStart{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeStart) ProtoMessage() {}

func (x *TradeStart) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeStart.ProtoReflect.Descriptor instead.
func (*TradeStart) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{27}
}

func (x *TradeStart) GetOtherUsername() string {
	if x != nil {
		return x.OtherUsername
	}
	return ""
}

// --- Admin ---
type AdminGiveItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetUsername string                 `protobuf:"bytes,1,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	ItemId         string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Amount         int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminGiveItemRequest) Reset() {
	*x = AdminGiveItemRequest{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGiveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGiveItemRequest) ProtoMessage() {}

func (x *AdminGiveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGiveItemRequest.ProtoReflect.Descriptor instead.
func (*AdminGiveItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{28}
}

func (x *AdminGiveItemRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

func (x *AdminGiveItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AdminGiveItemRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AdminBanRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetUsername  string                 `protobuf:"bytes,1,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminBanRequest) Reset() {
	*x = AdminBanRequest{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminBanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminBanRequest) ProtoMessage() {}

func (x *AdminBanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminBanRequest.ProtoReflect.Descriptor instead.
func (*AdminBanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{29}
}

func (x *AdminBanRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

func (x *AdminBanRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AdminBanRequest) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type AdminActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResponseText  string                 `protobuf:"bytes,2,opt,name=response_text,json=responseText,proto3" json:"response_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminActionResponse) Reset() {
	*x = AdminActionResponse{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminActionResponse) ProtoMessage() {}

func (x *AdminActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminActionResponse.ProtoReflect.Descriptor instead.
func (*AdminActionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{30}
}

func (x *AdminActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminActionResponse) GetResponseText() string {
	if x != nil {
		return x.ResponseText
	}
	return ""
}

type FriendListUpdate_Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	IsOnline      bool                   `protobuf:"varint,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // 'pending_sent', 'pending_received', 'accepted'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListUpdate_Friend) Reset() {
	*x = FriendListUpdate_Friend{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListUpdate_Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListUpdate_Friend) ProtoMessage() {}

func (x *FriendListUpdate_Friend) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListUpdate_Friend.ProtoReflect.Descriptor instead.
func (*FriendListUpdate_Friend) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{20, 0}
}

func (x *FriendListUpdate_Friend) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FriendListUpdate_Friend) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *FriendListUpdate_Friend) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TradeUpdate_TradeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeUpdate_TradeItem) Reset() {
	*x = TradeUpdate_TradeItem{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeUpdate_TradeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeUpdate_TradeItem) ProtoMessage() {}

func (x *TradeUpdate_TradeItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeUpdate_TradeItem.ProtoReflect.Descriptor instead.
func (*TradeUpdate_TradeItem) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{24, 0}
}

func (x *TradeUpdate_TradeItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *TradeUpdate_TradeItem) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TradeUpdate_TradeChao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChaoId        int64                  `protobuf:"varint,1,opt,name=chao_id,json=chaoId,proto3" json:"chao_id,omitempty"`
	ChaoName      string                 `protobuf:"bytes,2,opt,name=chao_name,json=chaoName,proto3" json:"chao_name,omitempty"`
	Rarity        string                 `protobuf:"bytes,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	ScenePath     string                 `protobuf:"bytes,4,opt,name=scene_path,json=scenePath,proto3" json:"scene_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeUpdate_TradeChao) Reset() {
	*x = TradeUpdate_TradeChao{}
	mi := &file_pkg_packets_game_packets_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeUpdate_TradeChao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeUpdate_TradeChao) ProtoMessage() {}

func (x *TradeUpdate_TradeChao) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_packets_game_packets_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeUpdate_TradeChao.ProtoReflect.Descriptor instead.
func (*TradeUpdate_TradeChao) Descriptor() ([]byte, []int) {
	return file_pkg_packets_game_packets_proto_rawDescGZIP(), []int{24, 1}
}

func (x *TradeUpdate_TradeChao) GetChaoId() int64 {
	if x != nil {
		return x.ChaoId
	}
	return 0
}

func (x *TradeUpdate_TradeChao) GetChaoName() string {
	if x != nil {
		return x.ChaoName
	}
	return ""
}

func (x *TradeUpdate_TradeChao) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *TradeUpdate_TradeChao) GetScenePath() string {
	if x != nil {
		return x.ScenePath
	}
	return ""
}

var File_pkg_packets_game_packets_proto protoreflect.FileDescriptor

const file_pkg_packets_game_packets_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/packets/game_packets.proto\x12\apackets\"\x86\x10\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12$\n" +
	"\x02id\x18\x03 \x01(\v2\x12.packets.IdMessageH\x00R\x02id\x12<\n" +
	"\rlogin_request\x18\x04 \x01(\v2\x15.packets.LoginRequestH\x00R\floginRequest\x12E\n" +
	"\x10register_request\x18\x05 \x01(\v2\x18.packets.RegisterRequestH\x00R\x0fregisterRequest\x12<\n" +
	"\rdeny_response\x18\a \x01(\v2\x15.packets.DenyResponseH\x00R\fdenyResponse\x12F\n" +
	"\x11save_data_request\x18\x19 \x01(\v2\x18.packets.SaveDataRequestH\x00R\x0fsaveDataRequest\x122\n" +
	"\vplayer_data\x18\x16 \x01(\v2\x0f.packets.PlayerH\x00R\n" +
	"playerData\x12I\n" +
	"\x12player_data_update\x18\x1d \x01(\v2\x19.packets.PlayerDataUpdateH\x00R\x10playerDataUpdate\x12L\n" +
	"\x13enter_world_request\x182 \x01(\v2\x1a.packets.EnterWorldRequestH\x00R\x11enterWorldRequest\x12-\n" +
	"\bmap_data\x183 \x01(\v2\x10.packets.MapDataH\x00R\amapData\x12L\n" +
	"\x13player_move_request\x184 \x01(\v2\x1a.packets.PlayerMoveRequestH\x00R\x11playerMoveRequest\x12U\n" +
	"\x16player_position_update\x185 \x01(\v2\x1d.packets.PlayerPositionUpdateH\x00R\x14playerPositionUpdate\x12C\n" +
	"\x10player_enter_map\x186 \x01(\v2\x17.packets.PlayerEnterMapH\x00R\x0eplayerEnterMap\x12C\n" +
	"\x10player_leave_map\x187 \x01(\v2\x17.packets.PlayerLeaveMapH\x00R\x0eplayerLeaveMap\x12*\n" +
	"\x04chat\x18\x14 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12L\n" +
	"\x13friend_request_list\x18\x1e \x01(\v2\x1a.packets.FriendRequestListH\x00R\x11friendRequestList\x12L\n" +
	"\x13friend_request_send\x18\x1f \x01(\v2\x1a.packets.FriendRequestSendH\x00R\x11friendRequestSend\x12X\n" +
	"\x17friend_request_response\x18  \x01(\v2\x1e.packets.FriendRequestResponseH\x00R\x15friendRequestResponse\x12<\n" +
	"\rfriend_remove\x18! \x01(\v2\x15.packets.FriendRemoveH\x00R\ffriendRemove\x12I\n" +
	"\x12friend_list_update\x18\" \x01(\v2\x19.packets.FriendListUpdateH\x00R\x10friendListUpdate\x12I\n" +
	"\x12trade_request_send\x18( \x01(\v2\x19.packets.TradeRequestSendH\x00R\x10tradeRequestSend\x12R\n" +
	"\x15trade_request_receive\x18) \x01(\v2\x1c.packets.TradeRequestReceiveH\x00R\x13tradeRequestReceive\x12U\n" +
	"\x16trade_request_response\x18* \x01(\v2\x1d.packets.TradeRequestResponseH\x00R\x14tradeRequestResponse\x129\n" +
	"\ftrade_update\x18+ \x01(\v2\x14.packets.TradeUpdateH\x00R\vtradeUpdate\x129\n" +
	"\ftrade_accept\x18, \x01(\v2\x14.packets.TradeAcceptH\x00R\vtradeAccept\x129\n" +
	"\ftrade_cancel\x18- \x01(\v2\x14.packets.TradeCancelH\x00R\vtradeCancel\x126\n" +
	"\vtrade_start\x18. \x01(\v2\x13.packets.TradeStartH\x00R\n" +
	"tradeStart\x12F\n" +
	"\x11admin_ban_request\x18\x1a \x01(\v2\x18.packets.AdminBanRequestH\x00R\x0fadminBanRequest\x12R\n" +
	"\x15admin_action_response\x18\x1b \x01(\v2\x1c.packets.AdminActionResponseH\x00R\x13adminActionResponse\x12V\n" +
	"\x17admin_give_item_request\x18\x1c \x01(\v2\x1d.packets.AdminGiveItemRequestH\x00R\x14adminGiveItemRequestB\x05\n" +
	"\x03msg\"\x13\n" +
	"\x11EnterWorldRequest\"P\n" +
	"\aMapData\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12.\n" +
	"\aplayers\x18\x02 \x03(\v2\x14.packets.OtherPlayerR\aplayers\"g\n" +
	"\x11PlayerMoveRequest\x12\x19\n" +
	"\btarget_x\x18\x01 \x01(\x05R\atargetX\x12\x19\n" +
	"\btarget_y\x18\x02 \x01(\x05R\atargetY\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\x05R\tdirection\"{\n" +
	"\x14PlayerPositionUpdate\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x13\n" +
	"\x05new_x\x18\x02 \x01(\x05R\x04newX\x12\x13\n" +
	"\x05new_y\x18\x03 \x01(\x05R\x04newY\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\x05R\tdirection\">\n" +
	"\x0ePlayerEnterMap\x12,\n" +
	"\x06player\x18\x01 \x01(\v2\x14.packets.OtherPlayerR\x06player\"-\n" +
	"\x0ePlayerLeaveMap\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"\x9d\x01\n" +
	"\vOtherPlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\x05R\tdirection\x12\x1b\n" +
	"\tsprite_id\x18\x06 \x01(\tR\bspriteId\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05color\x18\x03 \x01(\x05R\x05color\"&\n" +
	"\fDenyResponse\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\".\n" +
	"\x0fSaveDataRequest\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonData\"X\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x11baomain_json_data\x18\x03 \x01(\tR\x0fbaomainJsonData\">\n" +
	"\x10PlayerDataUpdate\x12*\n" +
	"\x11baomain_json_data\x18\x01 \x01(\tR\x0fbaomainJsonData\"\x1f\n" +
	"\vChatMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x13\n" +
	"\x11FriendRequestList\"<\n" +
	"\x11FriendRequestSend\x12'\n" +
	"\x0ftarget_username\x18\x01 \x01(\tR\x0etargetUsername\"X\n" +
	"\x15FriendRequestResponse\x12'\n" +
	"\x0ftarget_username\x18\x01 \x01(\tR\x0etargetUsername\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"7\n" +
	"\fFriendRemove\x12'\n" +
	"\x0ftarget_username\x18\x01 \x01(\tR\x0etargetUsername\"\xa9\x01\n" +
	"\x10FriendListUpdate\x12:\n" +
	"\afriends\x18\x01 \x03(\v2 .packets.FriendListUpdate.FriendR\afriends\x1aY\n" +
	"\x06Friend\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tis_online\x18\x02 \x01(\bR\bisOnline\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\";\n" +
	"\x10TradeRequestSend\x12'\n" +
	"\x0ftarget_username\x18\x01 \x01(\tR\x0etargetUsername\":\n" +
	"\x13TradeRequestReceive\x12#\n" +
	"\rfrom_username\x18\x01 \x01(\tR\ffromUsername\"W\n" +
	"\x14TradeRequestResponse\x12'\n" +
	"\x0ftarget_username\x18\x01 \x01(\tR\x0etargetUsername\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"\xe7\x02\n" +
	"\vTradeUpdate\x12 \n" +
	"\fis_locked_in\x18\x01 \x01(\bR\n" +
	"isLockedIn\x12\x14\n" +
	"\x05rings\x18\x02 \x01(\x03R\x05rings\x124\n" +
	"\x05items\x18\x03 \x03(\v2\x1e.packets.TradeUpdate.TradeItemR\x05items\x122\n" +
	"\x04chao\x18\x04 \x03(\v2\x1e.packets.TradeUpdate.TradeChaoR\x04chao\x1a<\n" +
	"\tTradeItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x1ax\n" +
	"\tTradeChao\x12\x17\n" +
	"\achao_id\x18\x01 \x01(\x03R\x06chaoId\x12\x1b\n" +
	"\tchao_name\x18\x02 \x01(\tR\bchaoName\x12\x16\n" +
	"\x06rarity\x18\x03 \x01(\tR\x06rarity\x12\x1d\n" +
	"\n" +
	"scene_path\x18\x04 \x01(\tR\tscenePath\"/\n" +
	"\vTradeAccept\x12 \n" +
	"\fis_locked_in\x18\x01 \x01(\bR\n" +
	"isLockedIn\"%\n" +
	"\vTradeCancel\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"3\n" +
	"\n" +
	"TradeStart\x12%\n" +
	"\x0eother_username\x18\x01 \x01(\tR\rotherUsername\"p\n" +
	"\x14AdminGiveItemRequest\x12'\n" +
	"\x0ftarget_username\x18\x01 \x01(\tR\x0etargetUsername\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"}\n" +
	"\x0fAdminBanRequest\x12'\n" +
	"\x0ftarget_username\x18\x01 \x01(\tR\x0etargetUsername\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x03R\x0fdurationSeconds\"T\n" +
	"\x13AdminActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rresponse_text\x18\x02 \x01(\tR\fresponseTextB\x1fZ\x1dchaogarden-server/pkg/packetsb\x06proto3"

var (
	file_pkg_packets_game_packets_proto_rawDescOnce sync.Once
	file_pkg_packets_game_packets_proto_rawDescData []byte
)

func file_pkg_packets_game_packets_proto_rawDescGZIP() []byte {
	file_pkg_packets_game_packets_proto_rawDescOnce.Do(func() {
		file_pkg_packets_game_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_packets_game_packets_proto_rawDesc), len(file_pkg_packets_game_packets_proto_rawDesc)))
	})
	return file_pkg_packets_game_packets_proto_rawDescData
}

var file_pkg_packets_game_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_pkg_packets_game_packets_proto_goTypes = []any{
	(*Packet)(nil),                  // 0: packets.Packet
	(*EnterWorldRequest)(nil),       // 1: packets.EnterWorldRequest
	(*MapData)(nil),                 // 2: packets.MapData
	(*PlayerMoveRequest)(nil),       // 3: packets.PlayerMoveRequest
	(*PlayerPositionUpdate)(nil),    // 4: packets.PlayerPositionUpdate
	(*PlayerEnterMap)(nil),          // 5: packets.PlayerEnterMap
	(*PlayerLeaveMap)(nil),          // 6: packets.PlayerLeaveMap
	(*OtherPlayer)(nil),             // 7: packets.OtherPlayer
	(*IdMessage)(nil),               // 8: packets.IdMessage
	(*LoginRequest)(nil),            // 9: packets.LoginRequest
	(*RegisterRequest)(nil),         // 10: packets.RegisterRequest
	(*DenyResponse)(nil),            // 11: packets.DenyResponse
	(*SaveDataRequest)(nil),         // 12: packets.SaveDataRequest
	(*Player)(nil),                  // 13: packets.Player
	(*PlayerDataUpdate)(nil),        // 14: packets.PlayerDataUpdate
	(*ChatMessage)(nil),             // 15: packets.ChatMessage
	(*FriendRequestList)(nil),       // 16: packets.FriendRequestList
	(*FriendRequestSend)(nil),       // 17: packets.FriendRequestSend
	(*FriendRequestResponse)(nil),   // 18: packets.FriendRequestResponse
	(*FriendRemove)(nil),            // 19: packets.FriendRemove
	(*FriendListUpdate)(nil),        // 20: packets.FriendListUpdate
	(*TradeRequestSend)(nil),        // 21: packets.TradeRequestSend
	(*TradeRequestReceive)(nil),     // 22: packets.TradeRequestReceive
	(*TradeRequestResponse)(nil),    // 23: packets.TradeRequestResponse
	(*TradeUpdate)(nil),             // 24: packets.TradeUpdate
	(*TradeAccept)(nil),             // 25: packets.TradeAccept
	(*TradeCancel)(nil),             // 26: packets.TradeCancel
	(*TradeStart)(nil),              // 27: packets.TradeStart
	(*AdminGiveItemRequest)(nil),    // 28: packets.AdminGiveItemRequest
	(*AdminBanRequest)(nil),         // 29: packets.AdminBanRequest
	(*AdminActionResponse)(nil),     // 30: packets.AdminActionResponse
	(*FriendListUpdate_Friend)(nil), // 31: packets.FriendListUpdate.Friend
	(*TradeUpdate_TradeItem)(nil),   // 32: packets.TradeUpdate.TradeItem
	(*TradeUpdate_TradeChao)(nil),   // 33: packets.TradeUpdate.TradeChao
}
var file_pkg_packets_game_packets_proto_depIdxs = []int32{
	8,  // 0: packets.Packet.id:type_name -> packets.IdMessage
	9,  // 1: packets.Packet.login_request:type_name -> packets.LoginRequest
	10, // 2: packets.Packet.register_request:type_name -> packets.RegisterRequest
	11, // 3: packets.Packet.deny_response:type_name -> packets.DenyResponse
	12, // 4: packets.Packet.save_data_request:type_name -> packets.SaveDataRequest
	13, // 5: packets.Packet.player_data:type_name -> packets.Player
	14, // 6: packets.Packet.player_data_update:type_name -> packets.PlayerDataUpdate
	1,  // 7: packets.Packet.enter_world_request:type_name -> packets.EnterWorldRequest
	2,  // 8: packets.Packet.map_data:type_name -> packets.MapData
	3,  // 9: packets.Packet.player_move_request:type_name -> packets.PlayerMoveRequest
	4,  // 10: packets.Packet.player_position_update:type_name -> packets.PlayerPositionUpdate
	5,  // 11: packets.Packet.player_enter_map:type_name -> packets.PlayerEnterMap
	6,  // 12: packets.Packet.player_leave_map:type_name -> packets.PlayerLeaveMap
	15, // 13: packets.Packet.chat:type_name -> packets.ChatMessage
	16, // 14: packets.Packet.friend_request_list:type_name -> packets.FriendRequestList
	17, // 15: packets.Packet.friend_request_send:type_name -> packets.FriendRequestSend
	18, // 16: packets.Packet.friend_request_response:type_name -> packets.FriendRequestResponse
	19, // 17: packets.Packet.friend_remove:type_name -> packets.FriendRemove
	20, // 18: packets.Packet.friend_list_update:type_name -> packets.FriendListUpdate
	21, // 19: packets.Packet.trade_request_send:type_name -> packets.TradeRequestSend
	22, // 20: packets.Packet.trade_request_receive:type_name -> packets.TradeRequestReceive
	23, // 21: packets.Packet.trade_request_response:type_name -> packets.TradeRequestResponse
	24, // 22: packets.Packet.trade_update:type_name -> packets.TradeUpdate
	25, // 23: packets.Packet.trade_accept:type_name -> packets.TradeAccept
	26, // 24: packets.Packet.trade_cancel:type_name -> packets.TradeCancel
	27, // 25: packets.Packet.trade_start:type_name -> packets.TradeStart
	29, // 26: packets.Packet.admin_ban_request:type_name -> packets.AdminBanRequest
	30, // 27: packets.Packet.admin_action_response:type_name -> packets.AdminActionResponse
	28, // 28: packets.Packet.admin_give_item_request:type_name -> packets.AdminGiveItemRequest
	7,  // 29: packets.MapData.players:type_name -> packets.OtherPlayer
	7,  // 30: packets.PlayerEnterMap.player:type_name -> packets.OtherPlayer
	31, // 31: packets.FriendListUpdate.friends:type_name -> packets.FriendListUpdate.Friend
	32, // 32: packets.TradeUpdate.items:type_name -> packets.TradeUpdate.TradeItem
	33, // 33: packets.TradeUpdate.chao:type_name -> packets.TradeUpdate.TradeChao
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_pkg_packets_game_packets_proto_init() }
func file_pkg_packets_game_packets_proto_init() {
	if File_pkg_packets_game_packets_proto != nil {
		return
	}
	file_pkg_packets_game_packets_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_Id)(nil),
		(*Packet_LoginRequest)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_DenyResponse)(nil),
		(*Packet_SaveDataRequest)(nil),
		(*Packet_PlayerData)(nil),
		(*Packet_PlayerDataUpdate)(nil),
		(*Packet_EnterWorldRequest)(nil),
		(*Packet_MapData)(nil),
		(*Packet_PlayerMoveRequest)(nil),
		(*Packet_PlayerPositionUpdate)(nil),
		(*Packet_PlayerEnterMap)(nil),
		(*Packet_PlayerLeaveMap)(nil),
		(*Packet_Chat)(nil),
		(*Packet_FriendRequestList)(nil),
		(*Packet_FriendRequestSend)(nil),
		(*Packet_FriendRequestResponse)(nil),
		(*Packet_FriendRemove)(nil),
		(*Packet_FriendListUpdate)(nil),
		(*Packet_TradeRequestSend)(nil),
		(*Packet_TradeRequestReceive)(nil),
		(*Packet_TradeRequestResponse)(nil),
		(*Packet_TradeUpdate)(nil),
		(*Packet_TradeAccept)(nil),
		(*Packet_TradeCancel)(nil),
		(*Packet_TradeStart)(nil),
		(*Packet_AdminBanRequest)(nil),
		(*Packet_AdminActionResponse)(nil),
		(*Packet_AdminGiveItemRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_packets_game_packets_proto_rawDesc), len(file_pkg_packets_game_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_packets_game_packets_proto_goTypes,
		DependencyIndexes: file_pkg_packets_game_packets_proto_depIdxs,
		MessageInfos:      file_pkg_packets_game_packets_proto_msgTypes,
	}.Build()
	File_pkg_packets_game_packets_proto = out.File
	file_pkg_packets_game_packets_proto_goTypes = nil
	file_pkg_packets_game_packets_proto_depIdxs = nil
}
